server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/booking/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payment/**
        - id: cab-service
          uri: lb://CAB-SERVICE
          predicates:
            - Path=/api/cab/**
